// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"03dao-admin/apps/user/view"
)

// Injectors from wire.go:

func InitApplication() (application, error) {
	//userView := view.NewUserView()
	_3dao_adminApplication := application{
		//userView: userView,
	}
	return _3dao_adminApplication, nil
}

// wire.go:

type application struct {
	userView *view.UserView
}
